### ISSUE TITLE
Feature: close glossary drawer by clicking outside of it

### ISSUE THREAD

**Issue by gemfarmer** [18F/glossary#11]
User testing for EITI has demonstrated that people instinctively want to close the glossary drawer by clicking outside of it. So..._drumroll_...new feature suggestion!

I added this to EITI, but as I had time to add the new 18F/glossary to our site, my additions are wrapped up in our bespoke version of the glossary. Eventually I would like to add this glossary, at which time it would be nice to have this feature available.

**Comment by noahmanger** [comment]
Love it. Let's add it.

**Comment by gemfarmer** [comment]
I'll make a PR for it when I have some free time. Probably not this week :/

**Comment by afeld** [comment]
Closed by #22.
