### ISSUE TITLE
A Plain Example

### ISSUE THREAD

**Issue by stphnwlkr** [18F/glossary#40]
I am a javascript noob so the example you have provided doesn't make a lot of sense to me. You require terms.json, but then do not use it because the terms are hardcoded into main.js. However if you remove the reference, nothing works. Is there a plain example that separate the various js pieces (panel, terms, accordion, etc.) into those that are actually used? The ability to link an external json file or call to an api and have terms returned based on a category is how I would like to use this.

**Comment by afeld** [comment]
`example/main.js` is [compiled from other files in the repository](https://github.com/18F/glossary/blob/f39c580f8832386be26a697ef93b32c4d8a95c44/package.json#L15), so don't worry too much about the contents of that file specifically. `example/init.js` is more like [what's in the README](https://github.com/18F/glossary#initialize).

> The ability to link an external json file

Does the above answer that question?

> call to an api and have terms returned based on a category

The `terms` variable value can come from anywhere, so you could make an AJAX request for the terms and initialize the Glossary afterwards, if you wanted.
